// REAPA MVP — Mock Data Layer
// Replace with Supabase queries when connecting to real DB

export type LeadScore = 'hot' | 'warm' | 'cold';
export type LeadSource = 'whatsapp' | 'email' | 'portal' | 'instagram' | 'facebook' | 'referral';
export type ClientStage = 'new' | 'qualified' | 'viewing' | 'offer' | 'closed';
export type TaskPriority = 'urgent' | 'high' | 'medium' | 'low';
export type TaskStatus = 'pending' | 'in_progress' | 'done' | 'overdue';

export interface Lead {
  id: string;
  name: string;
  phone: string;
  email: string;
  source: LeadSource;
  score: LeadScore;
  budget: number;
  location: string;
  propertyType: string;
  bedrooms: number;
  nationality: string;
  message: string;
  createdAt: string;
  lastContact: string;
  autoReplied: boolean;
  notes: string;
}

export interface Client {
  id: string;
  name: string;
  email: string;
  phone: string;
  nationality: string;
  stage: ClientStage;
  budget: number;
  preferredArea: string;
  propertyType: string;
  bedrooms: number;
  viewingsCount: number;
  lastContact: string;
  daysInactive: number;
  sentiment: 'positive' | 'neutral' | 'hesitant' | 'negative';
  agent: string;
  notes: string;
  createdAt: string;
}

export interface Task {
  id: string;
  title: string;
  description: string;
  priority: TaskPriority;
  status: TaskStatus;
  dueDate: string;
  dueTime: string;
  category: 'follow_up' | 'viewing' | 'document' | 'compliance' | 'call' | 'other';
  clientName?: string;
  autoGenerated: boolean;
}

export interface DashboardStats {
  totalLeads: number;
  hotLeads: number;
  activeClients: number;
  viewingsToday: number;
  pendingTasks: number;
  overdueTasks: number;
  dealsThisMonth: number;
  revenue: number;
  avgResponseTime: string;
  conversionRate: number;
}

// ---- Mock Data ----

export const leads: Lead[] = [
  {
    id: 'L001',
    name: 'James Harrison',
    phone: '+44 7700 900123',
    email: 'james.h@gmail.com',
    source: 'portal',
    score: 'hot',
    budget: 350000,
    location: "St Julian's",
    propertyType: 'Apartment',
    bedrooms: 2,
    nationality: 'British',
    message: 'Looking for a 2BR apartment in St Julian\'s, relocating for iGaming job in May. Need help with AIP permit.',
    createdAt: '2026-04-14T09:15:00',
    lastContact: '2026-04-14T09:15:00',
    autoReplied: true,
    notes: 'Auto-qualified: Budget matches area, timeline urgent (1 month). Pre-approved mortgage.'
  },
  {
    id: 'L002',
    name: 'Maria Borg',
    phone: '+356 9944 5566',
    email: 'maria.borg@outlook.com',
    source: 'referral',
    score: 'hot',
    budget: 280000,
    location: 'Sliema',
    propertyType: 'Apartment',
    bedrooms: 2,
    nationality: 'Maltese',
    message: 'Referred by Anna Camilleri. First-time buyer, looking for 2BR in Sliema or Gzira. Has bank pre-approval.',
    createdAt: '2026-04-13T14:30:00',
    lastContact: '2026-04-13T16:00:00',
    autoReplied: false,
    notes: 'Referral from previous client Anna. Very motivated — wants to move before summer.'
  },
  {
    id: 'L003',
    name: 'Lars Eriksson',
    phone: '+46 70 123 4567',
    email: 'lars.e@protonmail.com',
    source: 'instagram',
    score: 'warm',
    budget: 500000,
    location: 'Valletta',
    propertyType: 'Townhouse',
    bedrooms: 3,
    nationality: 'Swedish',
    message: 'Interested in a character property in Valletta or Birgu. Remote worker, no rush.',
    createdAt: '2026-04-12T18:45:00',
    lastContact: '2026-04-12T18:45:00',
    autoReplied: true,
    notes: 'High budget but no urgency. Nurturing sequence started.'
  },
  {
    id: 'L004',
    name: 'Ahmed Al-Rashid',
    phone: '+971 50 987 6543',
    email: 'ahmed.r@dubai-invest.com',
    source: 'email',
    score: 'warm',
    budget: 750000,
    location: 'Tigne Point',
    propertyType: 'Penthouse',
    bedrooms: 3,
    nationality: 'Emirati',
    message: 'Investment property, rental yield focus. Need AIP permit info. Want virtual tour.',
    createdAt: '2026-04-11T10:20:00',
    lastContact: '2026-04-12T11:00:00',
    autoReplied: true,
    notes: 'Non-EU buyer — AML check required. Sent AIP info automatically.'
  },
  {
    id: 'L005',
    name: 'Sophie Duval',
    phone: '+33 6 12 34 56 78',
    email: 'sophie.d@yahoo.fr',
    source: 'facebook',
    score: 'cold',
    budget: 200000,
    location: 'Bugibba',
    propertyType: 'Studio',
    bedrooms: 1,
    nationality: 'French',
    message: 'Just browsing, might buy something cheap for holidays.',
    createdAt: '2026-04-10T20:00:00',
    lastContact: '2026-04-10T20:00:00',
    autoReplied: true,
    notes: 'Low intent. Auto-added to monthly newsletter.'
  },
  {
    id: 'L006',
    name: 'Nikolai Petrov',
    phone: '+7 916 555 1234',
    email: 'n.petrov@mail.ru',
    source: 'whatsapp',
    score: 'hot',
    budget: 420000,
    location: 'Swieqi',
    propertyType: 'Apartment',
    bedrooms: 3,
    nationality: 'Russian',
    message: 'Relocating family to Malta. Need 3BR, good schools nearby. Budget flexible up to €450k.',
    createdAt: '2026-04-14T07:30:00',
    lastContact: '2026-04-14T08:00:00',
    autoReplied: true,
    notes: 'Family relocation — high motivation. Needs non-EU AIP permit. Auto-sent school area guide.'
  },
];

export const clients: Client[] = [
  {
    id: 'C001',
    name: 'David Chen',
    email: 'david.chen@techcorp.com',
    phone: '+852 9123 4567',
    nationality: 'Hong Kong',
    stage: 'viewing',
    budget: 600000,
    preferredArea: "St Julian's",
    propertyType: 'Apartment',
    bedrooms: 3,
    viewingsCount: 4,
    lastContact: '2026-04-12T15:00:00',
    daysInactive: 2,
    sentiment: 'positive',
    agent: 'You',
    notes: 'Very interested in Marina unit. 4th viewing scheduled for Friday.',
    createdAt: '2026-03-15T10:00:00'
  },
  {
    id: 'C002',
    name: 'Elena Vassallo',
    email: 'elena.v@gmail.com',
    phone: '+356 7912 3456',
    nationality: 'Maltese',
    stage: 'offer',
    budget: 320000,
    preferredArea: 'Mosta',
    propertyType: 'Maisonette',
    bedrooms: 3,
    viewingsCount: 6,
    lastContact: '2026-04-13T11:00:00',
    daysInactive: 1,
    sentiment: 'positive',
    agent: 'You',
    notes: 'Offer submitted at €305k. Waiting for seller response. Mortgage pre-approved.',
    createdAt: '2026-02-20T09:00:00'
  },
  {
    id: 'C003',
    name: 'Tom Williams',
    email: 'tom.w@igaming.mt',
    phone: '+44 7911 123456',
    nationality: 'British',
    stage: 'qualified',
    budget: 250000,
    preferredArea: 'Sliema',
    propertyType: 'Apartment',
    bedrooms: 2,
    viewingsCount: 0,
    lastContact: '2026-04-08T09:30:00',
    daysInactive: 6,
    sentiment: 'hesitant',
    agent: 'You',
    notes: 'iGaming relocation. Was keen but went quiet after rent comparison. Might be considering renting instead.',
    createdAt: '2026-03-28T14:00:00'
  },
  {
    id: 'C004',
    name: 'Katarina Novak',
    email: 'k.novak@fintech.io',
    phone: '+386 41 123 456',
    nationality: 'Slovenian',
    stage: 'viewing',
    budget: 400000,
    preferredArea: 'Valletta',
    propertyType: 'Townhouse',
    bedrooms: 2,
    viewingsCount: 2,
    lastContact: '2026-04-11T16:00:00',
    daysInactive: 3,
    sentiment: 'neutral',
    agent: 'You',
    notes: 'Wants character property. Liked VLT-203 but found it small. Need to find 2BR alternative.',
    createdAt: '2026-03-20T11:00:00'
  },
  {
    id: 'C005',
    name: 'Robert Grech',
    email: 'r.grech@gov.mt',
    phone: '+356 7987 6543',
    nationality: 'Maltese',
    stage: 'new',
    budget: 180000,
    preferredArea: 'Qormi',
    propertyType: 'Apartment',
    bedrooms: 2,
    viewingsCount: 0,
    lastContact: '2026-04-14T12:00:00',
    daysInactive: 0,
    sentiment: 'positive',
    agent: 'You',
    notes: 'First-time buyer. Government employee, stable income. Looking for affordable 2BR.',
    createdAt: '2026-04-14T12:00:00'
  },
];

export const tasks: Task[] = [
  {
    id: 'T001',
    title: 'Call back James Harrison',
    description: 'Hot lead — relocating for iGaming job in May. Needs 2BR in St Julian\'s + AIP permit help.',
    priority: 'urgent',
    status: 'pending',
    dueDate: '2026-04-14',
    dueTime: '10:00',
    category: 'call',
    clientName: 'James Harrison',
    autoGenerated: true
  },
  {
    id: 'T002',
    title: 'Call back Nikolai Petrov',
    description: 'Hot lead — family relocation, 3BR Swieqi, budget €420-450k. Non-EU — needs AIP.',
    priority: 'urgent',
    status: 'pending',
    dueDate: '2026-04-14',
    dueTime: '10:30',
    category: 'call',
    clientName: 'Nikolai Petrov',
    autoGenerated: true
  },
  {
    id: 'T003',
    title: 'Viewing: David Chen — Marina unit',
    description: '4th viewing of SJ-Marina-301. Client very interested. Prepare comparable prices.',
    priority: 'high',
    status: 'pending',
    dueDate: '2026-04-14',
    dueTime: '14:00',
    category: 'viewing',
    clientName: 'David Chen',
    autoGenerated: false
  },
  {
    id: 'T004',
    title: 'Follow up: Tom Williams (6 days inactive)',
    description: '⚠️ Ghost alert: Tom went quiet after rent comparison. Recommend: send buy-vs-rent analysis for Sliema.',
    priority: 'high',
    status: 'overdue',
    dueDate: '2026-04-12',
    dueTime: '09:00',
    category: 'follow_up',
    clientName: 'Tom Williams',
    autoGenerated: true
  },
  {
    id: 'T005',
    title: "Elena's offer — check seller response",
    description: 'Offer of €305k submitted yesterday. Call seller agent for update.',
    priority: 'high',
    status: 'pending',
    dueDate: '2026-04-14',
    dueTime: '11:00',
    category: 'call',
    clientName: 'Elena Vassallo',
    autoGenerated: true
  },
  {
    id: 'T006',
    title: 'Register rental contract — Unit 4B, Gzira',
    description: '⚠️ Housing Authority deadline in 2 days! Contract signed 28 days ago.',
    priority: 'urgent',
    status: 'overdue',
    dueDate: '2026-04-16',
    dueTime: '17:00',
    category: 'compliance',
    autoGenerated: true
  },
  {
    id: 'T007',
    title: 'Send market update to Katarina Novak',
    description: 'Auto follow-up: 3 days since last contact. Send new Valletta 2BR listings matching her criteria.',
    priority: 'medium',
    status: 'pending',
    dueDate: '2026-04-14',
    dueTime: '15:00',
    category: 'follow_up',
    clientName: 'Katarina Novak',
    autoGenerated: true
  },
  {
    id: 'T008',
    title: 'Prepare AML check — Ahmed Al-Rashid',
    description: 'Non-EU investor (Emirati). Run AML/KYC before proceeding with viewings.',
    priority: 'medium',
    status: 'pending',
    dueDate: '2026-04-15',
    dueTime: '10:00',
    category: 'compliance',
    clientName: 'Ahmed Al-Rashid',
    autoGenerated: true
  },
  {
    id: 'T009',
    title: 'Weekly Instagram post — New Listings',
    description: 'Auto-generated: "Top 5 New Listings This Week in Malta" carousel ready for review.',
    priority: 'low',
    status: 'pending',
    dueDate: '2026-04-14',
    dueTime: '18:00',
    category: 'other',
    autoGenerated: true
  },
];

export const dashboardStats: DashboardStats = {
  totalLeads: 24,
  hotLeads: 6,
  activeClients: 12,
  viewingsToday: 3,
  pendingTasks: 7,
  overdueTasks: 2,
  dealsThisMonth: 2,
  revenue: 28500,
  avgResponseTime: '1.8 min',
  conversionRate: 18.5,
};

export const funnelData = [
  { stage: 'New Leads', count: 24, color: '#6366f1' },
  { stage: 'Qualified', count: 15, color: '#8b5cf6' },
  { stage: 'Viewings', count: 8, color: '#a78bfa' },
  { stage: 'Offers', count: 3, color: '#c4b5fd' },
  { stage: 'Closed', count: 2, color: '#10b981' },
];

export const leadSourceData = [
  { source: 'WhatsApp', count: 8, percentage: 33 },
  { source: 'Portals', count: 6, percentage: 25 },
  { source: 'Instagram', count: 4, percentage: 17 },
  { source: 'Referrals', count: 3, percentage: 13 },
  { source: 'Email', count: 2, percentage: 8 },
  { source: 'Facebook', count: 1, percentage: 4 },
];
