"use client";
import { Card, Badge } from "@/components/UI";
import { tasks as mockTasks, type Task } from "@/lib/data";
import { Phone, Eye, Clock, FileText, Shield, CheckSquare, Sparkles, Check, Circle } from "lucide-react";
import { useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import "@/lib/i18n/config";

const priorityColors: Record<string, string>  = { urgent: "text-red-400", high: "text-orange-400", medium: "text-blue-400", low: "text-gray-400" };
const priorityBg: Record<string, string>       = { urgent: "bg-red-500/10 border-red-500/20", high: "bg-orange-500/10 border-orange-500/20", medium: "bg-blue-500/10 border-blue-500/20", low: "bg-[var(--bg)] border-[var(--border)]" };
const categoryIcons: Record<string, React.ReactNode> = {
  call:       <Phone size={14} className="text-blue-400" />,
  viewing:    <Eye size={14} className="text-purple-400" />,
  follow_up:  <Clock size={14} className="text-orange-400" />,
  document:   <FileText size={14} className="text-green-400" />,
  compliance: <Shield size={14} className="text-red-400" />,
  other:      <CheckSquare size={14} className="text-gray-400" />,
};

export default function TasksPage() {
  const { t } = useTranslation();
  const [tasksData, setTasksData] = useState<Task[]>(mockTasks);
  const [completed, setCompleted] = useState<Set<string>>(new Set());
  const [filter, setFilter] = useState<string>("all");

  useEffect(() => {
    fetch("/api/tasks").then(r => r.json()).then(setTasksData).catch(() => {});
  }, []);

  const aiGenerated = tasksData.filter(task => task.autoGenerated).length;

  const filtered = tasksData.filter(task => {
    if (filter === "urgent") return task.priority === "urgent" || task.status === "overdue";
    if (filter === "ai")     return task.autoGenerated;
    if (filter === "done")   return completed.has(task.id) || task.status === "done";
    return true;
  });

  const filterLabels: Record<string, string> = {
    all:    t("tasks.filterAll"),
    urgent: t("tasks.filterUrgent"),
    ai:     t("tasks.filterAI"),
    done:   t("tasks.filterDone"),
  };

  return (
    <div className="max-w-7xl mx-auto space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-xl font-bold">{t("tasks.title")}</h1>
          <p className="text-sm text-[var(--text-muted)]">{t("tasks.subtitle")}</p>
        </div>
        <div className="flex items-center gap-2 text-xs">
          <Sparkles size={12} className="text-indigo-400" />
          <span className="text-indigo-400">{aiGenerated}/{tasksData.length} {t("tasks.aiGenerated")}</span>
        </div>
      </div>

      {/* Filters */}
      <div className="flex bg-[var(--bg-card)] border border-[var(--border)] rounded-lg overflow-hidden self-start w-fit">
        {(["all", "urgent", "ai", "done"] as const).map(f => (
          <button key={f} onClick={() => setFilter(f)}
            className={`px-3 py-2 text-xs font-medium transition-colors ${filter === f ? "bg-[var(--accent)]/20 text-[var(--accent)]" : "text-[var(--text-muted)] hover:text-[var(--text)]"}`}>
            {filterLabels[f]}
          </button>
        ))}
      </div>

      {/* Tasks */}
      <div className="space-y-2">
        {filtered.map(task => {
          const isDone = completed.has(task.id) || task.status === "done";
          return (
            <Card key={task.id} className={`transition-all ${priorityBg[task.priority]} ${isDone ? "opacity-50" : ""}`}>
              <div className="flex items-start gap-3">
                <button onClick={() => setCompleted(prev => {
                  const next = new Set(prev);
                  if (next.has(task.id)) { next.delete(task.id); } else { next.add(task.id); }
                  return next;
                })} className="mt-0.5 flex-shrink-0">
                  {isDone
                    ? <Check size={16} className="text-emerald-400" />
                    : <Circle size={16} className="text-[var(--text-muted)]" />
                  }
                </button>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <span className={`font-medium text-sm ${isDone ? "line-through text-[var(--text-muted)]" : ""}`}>{task.title}</span>
                    {task.autoGenerated && (
                      <span className="flex items-center gap-1 text-[10px] text-indigo-400 bg-indigo-500/10 px-1.5 py-0.5 rounded">
                        <Sparkles size={9} /> {t("tasks.ai")}
                      </span>
                    )}
                  </div>
                  <div className="flex items-center gap-3 text-[11px] text-[var(--text-muted)] flex-wrap">
                    <span className="flex items-center gap-1">
                      {categoryIcons[task.category]}
                      {task.category.replace("_", " ")}
                    </span>
                    {task.clientName && <span>· {task.clientName}</span>}
                    {task.dueDate && (
                      <span className={`flex items-center gap-1 ${task.status === "overdue" ? "text-red-400" : ""}`}>
                        <Clock size={10} /> {task.dueDate} {task.dueTime}
                      </span>
                    )}
                  </div>
                </div>
                <div className={`text-[10px] font-semibold px-2 py-1 rounded-full flex-shrink-0 capitalize ${priorityColors[task.priority]}`}>
                  {task.priority}
                </div>
              </div>
            </Card>
          );
        })}
        {filtered.length === 0 && (
          <div className="text-center text-sm text-[var(--text-muted)] py-12">{t("tasks.noResults")}</div>
        )}
      </div>
    </div>
  );
}
