"use client";
import { Card, Badge } from "@/components/UI";
import { tasks, type Task } from "@/lib/data";
import { Phone, Eye, Clock, FileText, Shield, CheckSquare, Sparkles, Check, Circle } from "lucide-react";
import { useState } from "react";

const priorityColors: Record<string, string> = {
  urgent: "text-red-400", high: "text-orange-400", medium: "text-blue-400", low: "text-gray-400"
};
const priorityBg: Record<string, string> = {
  urgent: "bg-red-500/10 border-red-500/20", high: "bg-orange-500/10 border-orange-500/20",
  medium: "bg-blue-500/10 border-blue-500/20", low: "bg-[var(--bg)] border-[var(--border)]"
};
const categoryIcons: Record<string, React.ReactNode> = {
  call: <Phone size={14} className="text-blue-400" />,
  viewing: <Eye size={14} className="text-purple-400" />,
  follow_up: <Clock size={14} className="text-orange-400" />,
  document: <FileText size={14} className="text-green-400" />,
  compliance: <Shield size={14} className="text-red-400" />,
  other: <CheckSquare size={14} className="text-gray-400" />,
};

export default function TasksPage() {
  const [completed, setCompleted] = useState<Set<string>>(new Set());
  const [filter, setFilter] = useState<string>("all");

  const toggleComplete = (id: string) => {
    setCompleted(prev => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
  };

  const filtered = tasks.filter(t => {
    if (filter === "all") return true;
    if (filter === "ai") return t.autoGenerated;
    return t.category === filter;
  });

  const aiGenerated = tasks.filter(t => t.autoGenerated).length;

  return (
    <div className="max-w-7xl mx-auto space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-xl font-bold">Task Autopilot</h1>
          <p className="text-sm text-[var(--text-muted)]">AI-generated tasks & smart scheduling</p>
        </div>
        <div className="flex items-center gap-2">
          <span className="flex items-center gap-1 text-xs text-indigo-400 bg-indigo-500/10 px-2 py-1 rounded-lg">
            <Sparkles size={12} /> {aiGenerated}/{tasks.length} AI-generated
          </span>
        </div>
      </div>

      {/* Filter Tabs */}
      <div className="flex gap-2 flex-wrap overflow-x-auto pb-1 -mx-1 px-1">
        {[
          { key: "all", label: "All Tasks" },
          { key: "ai", label: "🤖 AI" },
          { key: "call", label: "📞 Calls" },
          { key: "viewing", label: "👁 Viewings" },
          { key: "follow_up", label: "⏰ Follow-ups" },
          { key: "compliance", label: "🛡 Compliance" },
        ].map(f => (
          <button
            key={f.key}
            onClick={() => setFilter(f.key)}
            className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors whitespace-nowrap ${
              filter === f.key
                ? "bg-[var(--accent)]/15 text-[var(--accent)] border-[var(--accent)]/30"
                : "bg-[var(--bg-card)] text-[var(--text-muted)] border-[var(--border)] hover:text-[var(--text)]"
            }`}
          >
            {f.label}
          </button>
        ))}
      </div>

      {/* Task Groups */}
      <div className="space-y-6">
        {/* Overdue */}
        {filtered.some(t => t.status === 'overdue') && (
          <div>
            <h3 className="text-xs uppercase tracking-wider text-red-400 font-medium mb-3">⚠️ Overdue</h3>
            <div className="space-y-2">
              {filtered.filter(t => t.status === 'overdue').map(task => (
                <TaskRow key={task.id} task={task} done={completed.has(task.id)} onToggle={() => toggleComplete(task.id)} />
              ))}
            </div>
          </div>
        )}

        {/* Today */}
        <div>
          <h3 className="text-xs uppercase tracking-wider text-[var(--text-muted)] font-medium mb-3">Today</h3>
          <div className="space-y-2">
            {filtered.filter(t => t.status !== 'overdue' && t.dueDate === '2026-04-14').map(task => (
              <TaskRow key={task.id} task={task} done={completed.has(task.id)} onToggle={() => toggleComplete(task.id)} />
            ))}
          </div>
        </div>

        {/* Upcoming */}
        {filtered.some(t => t.dueDate > '2026-04-14') && (
          <div>
            <h3 className="text-xs uppercase tracking-wider text-[var(--text-muted)] font-medium mb-3">Upcoming</h3>
            <div className="space-y-2">
              {filtered.filter(t => t.dueDate > '2026-04-14').map(task => (
                <TaskRow key={task.id} task={task} done={completed.has(task.id)} onToggle={() => toggleComplete(task.id)} />
              ))}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function TaskRow({ task, done, onToggle }: { task: Task; done: boolean; onToggle: () => void }) {
  return (
    <div className={`flex items-start gap-2.5 md:gap-3 p-3 md:p-4 rounded-xl border transition-all ${
      done ? 'opacity-40 bg-[var(--bg-card)] border-[var(--border)]' : priorityBg[task.priority]
    }`}>
      <button onClick={(e) => { e.stopPropagation(); onToggle(); }} className="mt-0.5 flex-shrink-0">
        {done
          ? <Check size={18} className="text-emerald-400" />
          : <Circle size={18} className={priorityColors[task.priority]} />
        }
      </button>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2 mb-0.5 flex-wrap">
          <span className={`text-sm font-medium ${done ? 'line-through' : ''}`}>{task.title}</span>
          {task.autoGenerated && (
            <span className="text-[10px] text-indigo-400 bg-indigo-500/10 px-1.5 py-0.5 rounded flex items-center gap-0.5">
              <Sparkles size={9} /> AI
            </span>
          )}
          {task.status === 'overdue' && <Badge variant="red">Overdue</Badge>}
        </div>
        <div className="text-xs text-[var(--text-muted)] truncate sm:whitespace-normal">{task.description}</div>
        {task.clientName && (
          <div className="text-[11px] text-[var(--accent)] mt-1">→ {task.clientName}</div>
        )}
      </div>

      <div className="flex items-center gap-2 md:gap-3 flex-shrink-0">
        <span className="hidden sm:block">{categoryIcons[task.category]}</span>
        <div className="text-right">
          <div className="text-xs font-medium">{task.dueTime}</div>
          <div className="text-[10px] text-[var(--text-muted)]">{task.dueDate === '2026-04-14' ? 'Today' : task.dueDate}</div>
        </div>
      </div>
    </div>
  );
}
