"use client";
import { Card } from "@/components/UI";
import { tasks as mockTasks, type Task } from "@/lib/data";
import { Phone, Eye, Clock, FileText, Shield, CheckSquare, Sparkles, Check, Circle, Plus, X } from "lucide-react";
import { useState, useEffect } from "react";
import { useTranslation } from "react-i18next";
import "@/lib/i18n/config";

const priorityColors: Record<string, string> = { urgent: "text-red-400", high: "text-orange-400", medium: "text-blue-400", low: "text-gray-400" };
const priorityBg: Record<string, string>     = { urgent: "bg-red-500/10 border-red-500/20", high: "bg-orange-500/10 border-orange-500/20", medium: "bg-blue-500/10 border-blue-500/20", low: "bg-[var(--bg)] border-[var(--border)]" };
const categoryIcons: Record<string, React.ReactNode> = {
  call:       <Phone size={14} className="text-blue-400" />,
  viewing:    <Eye size={14} className="text-purple-400" />,
  follow_up:  <Clock size={14} className="text-orange-400" />,
  document:   <FileText size={14} className="text-green-400" />,
  compliance: <Shield size={14} className="text-red-400" />,
  other:      <CheckSquare size={14} className="text-gray-400" />,
};

const PRIORITIES = ["urgent", "high", "medium", "low"] as const;
const CATEGORIES = ["call", "viewing", "follow_up", "document", "compliance", "other"] as const;

type NewTaskForm = { title: string; priority: string; type: string; due_at: string };

export default function TasksPage() {
  const { t } = useTranslation();
  const [tasksData, setTasksData]   = useState<Task[]>(mockTasks);
  const [dataLoaded, setTaskDataLoaded] = useState(false);
  const [completed, setCompleted]   = useState<Set<string>>(new Set());
  const [filter, setFilter]         = useState<string>("all");
  const [showForm, setShowForm]     = useState(false);
  const [creating, setCreating]     = useState(false);
  const [formError, setFormError]   = useState("");
  const [form, setForm]             = useState<NewTaskForm>({ title: "", priority: "medium", type: "other", due_at: "" });

  useEffect(() => {
    fetch("/api/tasks").then(r => r.json()).then(d => { setTasksData(d); setTaskDataLoaded(true); }).catch(() => { setTaskDataLoaded(true); });
  }, []);

  async function handleCreate(e: React.FormEvent) {
    e.preventDefault();
    if (!form.title.trim()) { setFormError("Title is required"); return; }
    setCreating(true);
    setFormError("");
    try {
      const res = await fetch("/api/tasks", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title:       form.title.trim(),
          priority:    form.priority,
          type:        form.type,
          due_at:      form.due_at || null,
          ai_generated: false,
        }),
      });
      if (res.ok) {
        const created = await res.json();
        const mapped: Task = {
          id:            created.id || String(Date.now()),
          title:         created.title,
          description:   "",
          priority:      (created.priority || "medium") as Task["priority"],
          status:        "pending",
          dueDate:       form.due_at ? form.due_at.split("T")[0] : "",
          dueTime:       "09:00",
          category:      (form.type || "other") as Task["category"],
          autoGenerated: false,
        };
        setTasksData(prev => [mapped, ...prev]);
        setForm({ title: "", priority: "medium", type: "other", due_at: "" });
        setShowForm(false);
      } else {
        setFormError("Failed to create task. Try again.");
      }
    } catch {
      setFormError("Network error. Try again.");
    } finally {
      setCreating(false);
    }
  }

  const aiGenerated = tasksData.filter(task => task.autoGenerated).length;

  const filtered = tasksData.filter(task => {
    if (filter === "urgent") return task.priority === "urgent" || task.status === "overdue";
    if (filter === "ai")     return task.autoGenerated;
    if (filter === "done")   return completed.has(task.id) || task.status === "done";
    return true;
  });

  const filterLabels: Record<string, string> = {
    all:    t("tasks.filterAll"),
    urgent: t("tasks.filterUrgent"),
    ai:     t("tasks.filterAI"),
    done:   t("tasks.filterDone"),
  };

  return (
    <div className="max-w-7xl mx-auto space-y-5">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1 className="text-xl font-bold">{t("tasks.title")}</h1>
          <p className="text-sm text-[var(--text-muted)]">{t("tasks.subtitle")}</p>
        </div>
        <div className="flex items-center gap-3">
          <div className="flex items-center gap-2 text-xs">
            <Sparkles size={12} className="text-indigo-400" />
            <span className="text-indigo-400">{aiGenerated}/{tasksData.length} {t("tasks.aiGenerated")}</span>
          </div>
          <button
            onClick={() => { setShowForm(v => !v); setFormError(""); }}
            className="flex items-center gap-1.5 px-3 py-1.5 bg-[var(--accent)] text-white text-xs font-medium rounded-lg hover:bg-[var(--accent-hover)] transition-colors"
          >
            {showForm ? <X size={13} /> : <Plus size={13} />}
            {showForm ? t("tasks.cancel") : t("tasks.newTask")}
          </button>
        </div>
      </div>

      {/* Quick task creation form */}
      {showForm && (
        <Card className="border-[var(--accent)]/30 bg-[var(--accent)]/5">
          <form onSubmit={handleCreate} className="space-y-3">
            <div className="flex flex-col sm:flex-row gap-3">
              <input
                type="text"
                placeholder={t("tasks.titlePlaceholder")}
                value={form.title}
                onChange={e => setForm(v => ({ ...v, title: e.target.value }))}
                autoFocus
                className="flex-1 px-3 py-2 bg-[var(--bg-card)] border border-[var(--border)] rounded-lg text-sm placeholder:text-[var(--text-muted)] focus:outline-none focus:border-[var(--accent)]"
              />
              <select
                value={form.priority}
                onChange={e => setForm(v => ({ ...v, priority: e.target.value }))}
                className="px-3 py-2 bg-[var(--bg-card)] border border-[var(--border)] rounded-lg text-sm focus:outline-none focus:border-[var(--accent)]"
              >
                {PRIORITIES.map(p => <option key={p} value={p}>{p.charAt(0).toUpperCase() + p.slice(1)}</option>)}
              </select>
              <select
                value={form.type}
                onChange={e => setForm(v => ({ ...v, type: e.target.value }))}
                className="px-3 py-2 bg-[var(--bg-card)] border border-[var(--border)] rounded-lg text-sm focus:outline-none focus:border-[var(--accent)]"
              >
                {CATEGORIES.map(c => <option key={c} value={c}>{c.replace("_", " ")}</option>)}
              </select>
              <input
                type="datetime-local"
                value={form.due_at}
                onChange={e => setForm(v => ({ ...v, due_at: e.target.value }))}
                className="px-3 py-2 bg-[var(--bg-card)] border border-[var(--border)] rounded-lg text-sm focus:outline-none focus:border-[var(--accent)]"
              />
            </div>
            {formError && <p className="text-xs text-red-400">{formError}</p>}
            <div className="flex gap-2">
              <button
                type="submit"
                disabled={creating}
                className="px-4 py-1.5 bg-[var(--accent)] text-white text-xs font-medium rounded-lg hover:bg-[var(--accent-hover)] disabled:opacity-60 transition-colors"
              >
                {creating ? t("tasks.creating") : t("tasks.create")}
              </button>
              <button
                type="button"
                onClick={() => { setShowForm(false); setFormError(""); }}
                className="px-4 py-1.5 bg-[var(--bg)] text-[var(--text-muted)] text-xs rounded-lg border border-[var(--border)] hover:bg-[var(--bg-card-hover)] transition-colors"
              >
                {t("tasks.cancel")}
              </button>
            </div>
          </form>
        </Card>
      )}

      {/* Filters */}
      <div className="flex bg-[var(--bg-card)] border border-[var(--border)] rounded-lg overflow-hidden self-start w-fit">
        {(["all", "urgent", "ai", "done"] as const).map(f => (
          <button key={f} onClick={() => setFilter(f)}
            className={`px-3 py-2 text-xs font-medium transition-colors ${filter === f ? "bg-[var(--accent)]/20 text-[var(--accent)]" : "text-[var(--text-muted)] hover:text-[var(--text)]"}`}>
            {filterLabels[f]}
          </button>
        ))}
      </div>

      {/* Task list */}
      <div className="space-y-2">
        {filtered.map(task => {
          const isDone = completed.has(task.id) || task.status === "done";
          return (
            <Card key={task.id} className={`transition-all ${priorityBg[task.priority]} ${isDone ? "opacity-50" : ""}`}>
              <div className="flex items-start gap-3">
                <button onClick={() => setCompleted(prev => {
                  const next = new Set(prev);
                  if (next.has(task.id)) { next.delete(task.id); } else { next.add(task.id); }
                  return next;
                })} className="mt-0.5 flex-shrink-0">
                  {isDone
                    ? <Check size={16} className="text-emerald-400" />
                    : <Circle size={16} className="text-[var(--text-muted)]" />
                  }
                </button>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1 flex-wrap">
                    <span className={`font-medium text-sm ${isDone ? "line-through text-[var(--text-muted)]" : ""}`}>{task.title}</span>
                    {task.autoGenerated && (
                      <span className="flex items-center gap-1 text-[10px] text-indigo-400 bg-indigo-500/10 px-1.5 py-0.5 rounded">
                        <Sparkles size={9} /> {t("tasks.ai")}
                      </span>
                    )}
                  </div>
                  <div className="flex items-center gap-3 text-[11px] text-[var(--text-muted)] flex-wrap">
                    <span className="flex items-center gap-1">
                      {categoryIcons[task.category]}
                      {task.category.replace("_", " ")}
                    </span>
                    {task.clientName && <span>· {task.clientName}</span>}
                    {task.dueDate && (
                      <span className={`flex items-center gap-1 ${task.status === "overdue" ? "text-red-400" : ""}`}>
                        <Clock size={10} /> {task.dueDate} {task.dueTime}
                      </span>
                    )}
                  </div>
                </div>
                <div className={`text-[10px] font-semibold px-2 py-1 rounded-full flex-shrink-0 capitalize ${priorityColors[task.priority]}`}>
                  {task.priority}
                </div>
              </div>
            </Card>
          );
        })}
        {filtered.length === 0 && (
          <div className="text-center text-sm text-[var(--text-muted)] py-12">{t("tasks.noResults")}</div>
        )}
      </div>
    </div>
  );
}
