import { NextResponse } from "next/server";
import { createAdminClient } from "@/lib/supabase/server";

type SupabaseTask = {
  id: string; title: string; description: string | null; type: string | null;
  priority: string | null; status: string | null; due_at: string | null;
  ai_generated: boolean | null;
  leads?: { name: string } | null;
  clients?: { name: string } | null;
};

function mapPriority(p: string | null): "urgent" | "high" | "medium" | "low" {
  if (p === "critical") return "urgent";
  if (p === "high") return "high";
  if (p === "low") return "low";
  return "medium";
}
function mapStatus(s: string | null): "pending" | "in_progress" | "done" | "overdue" {
  if (s === "completed") return "done";
  if (s === "in_progress") return "in_progress";
  if (s === "cancelled") return "done";
  return "pending";
}
function mapCategory(t: string | null): string {
  if (t === "follow_up") return "follow_up";
  if (t === "viewing") return "viewing";
  if (t === "document") return "document";
  if (t === "compliance") return "compliance";
  if (t === "offer") return "call";
  return "other";
}

export async function GET() {
  try {
    const admin = createAdminClient();
    const { data, error } = await admin
      .from("tasks")
      .select("id, title, description, type, priority, status, due_at, ai_generated, leads(name), clients(name)")
      .order("due_at", { ascending: true });
    if (error) throw error;
    const tasks = (data as SupabaseTask[]).map((t) => {
      const dueDate = t.due_at ? new Date(t.due_at) : null;
      const isOverdue = dueDate && dueDate < new Date() && t.status === "pending";
      const clientName = (t.clients && (t.clients as {name:string}).name) || (t.leads && (t.leads as {name:string}).name) || undefined;
      return {
        id: t.id, title: t.title, description: t.description || "",
        priority: mapPriority(t.priority),
        status: isOverdue ? "overdue" : mapStatus(t.status),
        dueDate: dueDate ? dueDate.toISOString().split("T")[0] : "",
        dueTime: dueDate ? dueDate.toTimeString().slice(0, 5) : "09:00",
        category: mapCategory(t.type), clientName, autoGenerated: t.ai_generated || false,
      };
    });
    return NextResponse.json(tasks);
  } catch (err) {
    console.error("[/api/tasks]", err);
    return NextResponse.json([], { status: 500 });
  }
}

export async function POST(request: Request) {
  try {
    const body = await request.json() as {
      title:        string;
      priority?:    string;
      type?:        string;
      due_at?:      string | null;
      description?: string | null;
      ai_generated?: boolean;
    };

    if (!body.title?.trim()) {
      return NextResponse.json({ error: "title is required" }, { status: 400 });
    }

    const admin = createAdminClient();
    const { data, error } = await admin
      .from("tasks")
      .insert({
        title:        body.title.trim(),
        priority:     body.priority     || "medium",
        type:         body.type         || "other",
        status:       "pending",
        due_at:       body.due_at       || null,
        description:  body.description  || null,
        ai_generated: body.ai_generated ?? false,
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
      } as any)
      .select()
      .single();

    if (error) throw error;
    return NextResponse.json(data, { status: 201 });
  } catch (err) {
    console.error("[POST /api/tasks]", err);
    return NextResponse.json({ error: "Failed to create task" }, { status: 500 });
  }
}
