import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — REAPA",
  description: "REAPA Terms of Service for the beta platform. Malta law. GDPR compliant.",
  robots: { index: true, follow: true },
};

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 text-[var(--text-primary,#f1f5f9)] prose prose-invert prose-sm">
      <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-400 mb-8">
        Last updated: April 17, 2026 &nbsp;·&nbsp; Effective: April 17, 2026
      </p>

      {/* 1. Acceptance */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
        <p>
          By accessing or using REAPA (&quot;Service&quot;, &quot;Platform&quot;) you agree
          to be bound by these Terms of Service. If you do not agree, do not use the Service.
        </p>
        <p className="mt-2">
          The Service is operated by <strong>Artur Malokhmetov</strong>, Malta.
          Contact:{" "}
          <a href="mailto:legal@reapa.ai" className="text-indigo-400 underline">
            legal@reapa.ai
          </a>
        </p>
      </section>

      {/* 2. Beta disclaimer */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">2. Beta Disclaimer</h2>
        <div className="bg-yellow-900/20 border border-yellow-600/30 rounded-xl p-4 mb-4">
          <p className="text-yellow-300 text-sm font-medium">⚠️ Beta software — use with caution</p>
        </div>
        <p>
          REAPA is currently in <strong>beta</strong>. The Service is provided for evaluation
          and testing purposes. It may contain bugs, errors, or incomplete features.
          We reserve the right to:
        </p>
        <ul className="list-disc pl-6 space-y-1 mt-2">
          <li>Modify, suspend, or discontinue the Service at any time without notice.</li>
          <li>Reset or wipe beta data without liability.</li>
          <li>Change pricing, features, or access conditions before general availability.</li>
        </ul>
        <p className="mt-3">
          <strong>Do not use REAPA as your sole system of record during the beta period.</strong>
        </p>
      </section>

      {/* 3. AI content disclaimer */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">3. AI-Generated Content</h2>
        <p>
          REAPA uses artificial intelligence (Google Gemini) to generate responses, summaries,
          and suggestions. You acknowledge that:
        </p>
        <ul className="list-disc pl-6 space-y-2 mt-2">
          <li>
            AI-generated content may be <strong>inaccurate, incomplete, or outdated</strong>.
            It is provided for informational purposes only and does not constitute legal,
            financial, or compliance advice.
          </li>
          <li>
            You are responsible for verifying any AI-generated information before acting on it,
            particularly regarding AML/KYC obligations, property valuations, or client advice.
          </li>
          <li>
            REAPA does not guarantee the accuracy, reliability, or fitness for purpose of any
            AI output.
          </li>
          <li>
            <strong>EU AI Act (Regulation (EU) 2024/1689) notice:</strong> REAPA includes an
            AI system as defined by the EU AI Act. Responses are generated by AI and labelled
            accordingly in the interface.
          </li>
        </ul>
      </section>

      {/* 4. User data ownership */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">4. Data Ownership</h2>
        <p>
          You own all data you import or enter into REAPA (leads, client records, notes).
          By using the Service, you grant REAPA a limited, non-exclusive licence to process
          that data solely to provide the Service.
        </p>
        <p className="mt-2">
          We will never sell your client or lead data to third parties. You may export or
          delete your data at any time. See our{" "}
          <Link href="/privacy" className="text-indigo-400 underline">Privacy Policy</Link>{" "}
          for details.
        </p>
      </section>

      {/* 5. Permitted use */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">5. Permitted Use</h2>
        <p>You agree not to:</p>
        <ul className="list-disc pl-6 space-y-1 mt-2">
          <li>Use the Service for any unlawful purpose, including money laundering.</li>
          <li>Attempt to reverse-engineer, decompile, or extract source code.</li>
          <li>Use automated scripts or bots to abuse the API or exceed fair-use limits.</li>
          <li>Upload content that is defamatory, illegal, or infringes third-party rights.</li>
          <li>Share login credentials or allow unauthorised access to your account.</li>
        </ul>
      </section>

      {/* 6. AML compliance */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">6. AML / Regulatory Compliance</h2>
        <p>
          Real estate professionals in Malta are subject to AML/CFT obligations under the
          Prevention of Money Laundering Act (Cap. 373) and EU AMLD directives. REAPA
          provides tools to assist with compliance checklists but does{" "}
          <strong>not</strong> constitute a regulated compliance service.
        </p>
        <p className="mt-2">
          You remain solely responsible for complying with all applicable AML, KYC, and
          regulatory obligations in your jurisdiction.
        </p>
      </section>

      {/* 7. Intellectual property */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">7. Intellectual Property</h2>
        <p>
          All rights in the REAPA platform, including software, design, trademarks, and
          brand assets, are owned by Artur Malokhmetov. No licence to copy or redistribute
          is granted except as expressly stated.
        </p>
      </section>

      {/* 8. Limitation of liability */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">8. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by Malta law, REAPA and its operator shall not
          be liable for any indirect, incidental, special, or consequential damages
          (including loss of revenue, data, or business opportunity) arising from your
          use of the Service.
        </p>
        <p className="mt-2">
          Our total aggregate liability to you for any claim shall not exceed the amount
          you paid for the Service in the 3 months preceding the claim (or €50, whichever
          is greater). During the free beta period, our liability is capped at €50.
        </p>
      </section>

      {/* 9. Termination */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">9. Termination</h2>
        <p>
          You may close your account at any time via{" "}
          <Link href="/settings" className="text-indigo-400 underline">Settings</Link>.
          We reserve the right to suspend or terminate accounts that violate these Terms
          or applicable law, with or without notice.
        </p>
      </section>

      {/* 10. Governing law */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">10. Governing Law &amp; Disputes</h2>
        <p>
          These Terms are governed by the laws of the Republic of Malta. Any disputes
          shall be subject to the exclusive jurisdiction of the courts of Malta.
          If you are a consumer in the EU, you also have the right to use the{" "}
          <a
            href="https://ec.europa.eu/consumers/odr"
            target="_blank"
            rel="noopener noreferrer"
            className="text-indigo-400 underline"
          >
            EU Online Dispute Resolution platform
          </a>
          .
        </p>
      </section>

      {/* 11. Changes */}
      <section className="mb-8">
        <h2 className="text-xl font-semibold mb-3">11. Changes to These Terms</h2>
        <p>
          We may update these Terms. Continued use after notification of changes
          constitutes acceptance. Material changes affecting your rights will be
          communicated by email at least 14 days in advance.
        </p>
      </section>

      <hr className="border-gray-700 my-8" />
      <p className="text-xs text-gray-500">Governing law: Republic of Malta</p>
      <div className="mt-6 flex gap-4 text-sm">
        <Link href="/privacy" className="text-indigo-400 underline">Privacy Policy</Link>
        <Link href="/" className="text-gray-400 hover:text-white">← Back to app</Link>
      </div>
    </div>
  );
}
