import { describe, it, expect } from "vitest";
import {
  leads,
  clients,
  tasks,
  dashboardStats,
  funnelData,
  leadSourceData,
} from "@/lib/data";

describe("lib/data — leads", () => {
  it("exports a non-empty leads array", () => {
    expect(Array.isArray(leads)).toBe(true);
    expect(leads.length).toBeGreaterThanOrEqual(5);
  });

  it("every lead has required string fields", () => {
    for (const lead of leads) {
      expect(typeof lead.id).toBe("string");
      expect(typeof lead.name).toBe("string");
      expect(typeof lead.phone).toBe("string");
      expect(typeof lead.email).toBe("string");
      expect(typeof lead.location).toBe("string");
      expect(typeof lead.propertyType).toBe("string");
      expect(typeof lead.nationality).toBe("string");
      expect(typeof lead.message).toBe("string");
      expect(typeof lead.notes).toBe("string");
      expect(typeof lead.createdAt).toBe("string");
      expect(typeof lead.lastContact).toBe("string");
    }
  });

  it("every lead has valid score", () => {
    const valid = ["hot", "warm", "cold"];
    for (const lead of leads) {
      expect(valid).toContain(lead.score);
    }
  });

  it("every lead has valid source", () => {
    const valid = ["whatsapp", "email", "portal", "instagram", "facebook", "referral"];
    for (const lead of leads) {
      expect(valid).toContain(lead.source);
    }
  });

  it("every lead has numeric budget and bedrooms", () => {
    for (const lead of leads) {
      expect(typeof lead.budget).toBe("number");
      expect(lead.budget).toBeGreaterThan(0);
      expect(typeof lead.bedrooms).toBe("number");
      expect(lead.bedrooms).toBeGreaterThan(0);
    }
  });

  it("every lead has boolean autoReplied", () => {
    for (const lead of leads) {
      expect(typeof lead.autoReplied).toBe("boolean");
    }
  });

  it("includes at least one hot and one warm lead", () => {
    expect(leads.some((l) => l.score === "hot")).toBe(true);
    expect(leads.some((l) => l.score === "warm")).toBe(true);
  });

  it("lead ids are unique", () => {
    const ids = leads.map((l) => l.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});

describe("lib/data — clients", () => {
  it("exports a non-empty clients array", () => {
    expect(Array.isArray(clients)).toBe(true);
    expect(clients.length).toBeGreaterThanOrEqual(2);
  });

  it("every client has required fields", () => {
    for (const client of clients) {
      expect(typeof client.id).toBe("string");
      expect(typeof client.name).toBe("string");
      expect(typeof client.email).toBe("string");
      expect(typeof client.phone).toBe("string");
      expect(typeof client.nationality).toBe("string");
      expect(typeof client.agent).toBe("string");
      expect(typeof client.notes).toBe("string");
    }
  });

  it("every client has valid stage", () => {
    const valid = ["new", "qualified", "viewing", "offer", "closed"];
    for (const client of clients) {
      expect(valid).toContain(client.stage);
    }
  });

  it("every client has valid sentiment", () => {
    const valid = ["positive", "neutral", "hesitant", "negative"];
    for (const client of clients) {
      expect(valid).toContain(client.sentiment);
    }
  });

  it("every client has numeric budget, viewingsCount, daysInactive, bedrooms", () => {
    for (const client of clients) {
      expect(typeof client.budget).toBe("number");
      expect(typeof client.viewingsCount).toBe("number");
      expect(typeof client.daysInactive).toBe("number");
      expect(typeof client.bedrooms).toBe("number");
    }
  });

  it("client ids are unique", () => {
    const ids = clients.map((c) => c.id);
    expect(new Set(ids).size).toBe(ids.length);
  });
});

describe("lib/data — tasks", () => {
  it("exports a non-empty tasks array", () => {
    expect(Array.isArray(tasks)).toBe(true);
    expect(tasks.length).toBeGreaterThanOrEqual(5);
  });

  it("every task has required fields", () => {
    for (const task of tasks) {
      expect(typeof task.id).toBe("string");
      expect(typeof task.title).toBe("string");
      expect(typeof task.description).toBe("string");
      expect(typeof task.dueDate).toBe("string");
      expect(typeof task.dueTime).toBe("string");
      expect(typeof task.autoGenerated).toBe("boolean");
    }
  });

  it("every task has valid priority", () => {
    const valid = ["urgent", "high", "medium", "low"];
    for (const task of tasks) {
      expect(valid).toContain(task.priority);
    }
  });

  it("every task has valid status", () => {
    const valid = ["pending", "in_progress", "done", "overdue"];
    for (const task of tasks) {
      expect(valid).toContain(task.status);
    }
  });

  it("every task has valid category", () => {
    const valid = ["follow_up", "viewing", "document", "compliance", "call", "other"];
    for (const task of tasks) {
      expect(valid).toContain(task.category);
    }
  });

  it("task ids are unique", () => {
    const ids = tasks.map((t) => t.id);
    expect(new Set(ids).size).toBe(ids.length);
  });

  it("autoGenerated tasks exist", () => {
    expect(tasks.some((t) => t.autoGenerated === true)).toBe(true);
  });
});

describe("lib/data — dashboardStats", () => {
  it("has all required numeric fields", () => {
    expect(typeof dashboardStats.totalLeads).toBe("number");
    expect(typeof dashboardStats.hotLeads).toBe("number");
    expect(typeof dashboardStats.activeClients).toBe("number");
    expect(typeof dashboardStats.viewingsToday).toBe("number");
    expect(typeof dashboardStats.pendingTasks).toBe("number");
    expect(typeof dashboardStats.overdueTasks).toBe("number");
    expect(typeof dashboardStats.dealsThisMonth).toBe("number");
    expect(typeof dashboardStats.revenue).toBe("number");
    expect(typeof dashboardStats.conversionRate).toBe("number");
  });

  it("has avgResponseTime as string", () => {
    expect(typeof dashboardStats.avgResponseTime).toBe("string");
    expect(dashboardStats.avgResponseTime.length).toBeGreaterThan(0);
  });

  it("conversionRate is in range 0–100", () => {
    expect(dashboardStats.conversionRate).toBeGreaterThanOrEqual(0);
    expect(dashboardStats.conversionRate).toBeLessThanOrEqual(100);
  });

  it("hotLeads <= totalLeads", () => {
    expect(dashboardStats.hotLeads).toBeLessThanOrEqual(dashboardStats.totalLeads);
  });

  it("overdueTasks <= pendingTasks", () => {
    expect(dashboardStats.overdueTasks).toBeLessThanOrEqual(dashboardStats.pendingTasks);
  });
});

describe("lib/data — funnelData", () => {
  it("exports a non-empty funnel array", () => {
    expect(Array.isArray(funnelData)).toBe(true);
    expect(funnelData.length).toBeGreaterThanOrEqual(3);
  });

  it("each stage has stage/count/color", () => {
    for (const stage of funnelData) {
      expect(typeof stage.stage).toBe("string");
      expect(typeof stage.count).toBe("number");
      expect(typeof stage.color).toBe("string");
      expect(stage.color).toMatch(/^#[0-9a-fA-F]{6}$/);
    }
  });

  it("funnel is top-heavy (first stage has most leads)", () => {
    expect(funnelData[0].count).toBeGreaterThan(funnelData[funnelData.length - 1].count);
  });
});

describe("lib/data — leadSourceData", () => {
  it("exports a non-empty sources array", () => {
    expect(Array.isArray(leadSourceData)).toBe(true);
    expect(leadSourceData.length).toBeGreaterThanOrEqual(4);
  });

  it("each source has source/count/percentage", () => {
    for (const src of leadSourceData) {
      expect(typeof src.source).toBe("string");
      expect(typeof src.count).toBe("number");
      expect(typeof src.percentage).toBe("number");
    }
  });

  it("percentages sum to ~100", () => {
    const total = leadSourceData.reduce((sum, s) => sum + s.percentage, 0);
    expect(total).toBeGreaterThanOrEqual(90);
    expect(total).toBeLessThanOrEqual(110);
  });
});
